name: 🚢 Deploy staging

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    uses: ./.github/workflows/reusable-build-and-push-docker-image.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: write

  deploy:
    environment: staging
    name: Deploy to staging
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy image ${{ needs.build.outputs.image-version }} to staging
        env:
          IMAGE_VERSION: ${{ needs.build.outputs.image-version }}
        # language=sh
        run: |
          echo "Deploying ${IMAGE_VERSION} to staging"
