name: 🚢 Deploy production

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    uses: ./.github/workflows/reusable-build-and-push-docker-image.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: write

  deploy:
    environment: production
    name: Deploy to production
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: echo "Deploying to production"
