name: 🚢 Deploy production

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    uses: ./.github/workflows/reusable-build-and-push-docker-image.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: write

  deploy:
    environment:
      name: production
      url: https://app.example.com
    name: Deploy image ${{ needs.build.outputs.image-version }} to production
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy image
        env:
          IMAGE_VERSION: ${{ needs.build.outputs.image-version }}
        # language=sh
        run: |
          echo "::notice::Deploying ${IMAGE_VERSION} to production"
