name: ⚒️ Build and Push Docker Image

on:
  workflow_call:
    outputs:
      image-version:
        description: The version of the Docker image
        value: ${{ jobs.resolve-image-version.outputs.image-version }}

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        # language=sh
        run: |
          docker run --rm --interactive ghcr.io/hadolint/hadolint hadolint --ignore DL3008 - < Dockerfile

  resolve-image-version:
    name: Resolve Docker Image Version
    runs-on: ubuntu-latest

    outputs:
      image-version: ${{ steps.resolve-image-version.outputs.image-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Resolve Docker image version
        id: resolve-image-version
        # language=sh
        run: |
          image_version=$(git rev-parse --short=8 HEAD)
          echo "image-version=${image_version}" >> "${GITHUB_OUTPUT}"

  build-and-push-docker-image:
    name: Build and push Docker image
    needs:
      - lint
      - resolve-image-version
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      # Ability to push image to GitHub container registry
      packages: write

    env:
      GHCR_REGISTRY: ghcr.io
      GHCR_REPOSITORY: ghcr.io/${{ github.repository }}

    steps:
      - uses: actions/checkout@v4

      # Extract tags and labels from the GitHub context
      - name: Prepare image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_REPOSITORY }}

          labels: |
            org.opencontainers.image.description=Example

          # Set the highest priority for sha-* tag, so it can be used as the main image tag,
          # see https://github.com/docker/metadata-action?tab=readme-ov-file#priority-attribute
          tags: |
            # Set the highest priority for sha tag, so it can be used as the main image tag
            type=raw,value=${{ needs.resolve-image-version.outputs.image-version }},priority=10000
            
            # Set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - uses: docker/setup-buildx-action@v3
        with:
          install: true # Sets up docker build command as an alias to docker buildx

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REPOSITORY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=${{ env.GHCR_REPOSITORY }}:cache
          # Export layers from all build stages
          cache-to: type=registry,ref=${{ env.GHCR_REPOSITORY }}:cache,mode=max
          push: true
          # Disable adding additional Docker metadata, therefore the image is more compliant with OCI spec.
          # See https://github.com/docker/build-push-action/issues/820
          provenance: false

      - uses: actions/github-script@v7
        env:
          IMAGE_VERSION: ${{ needs.resolve-image-version.outputs.image-version }}
        with:
          # language=javascript
          script: |
            const { IMAGE_VERSION } = process.env;
            core.summary.addRaw(`Image version: <code>${IMAGE_VERSION}</code>`, true);
            core.summary.write();
